burgero/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import home, category_filter

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('filter/<str:category>/', category_filter, name="filter"),
    path('accounts/', include("accounts.urls")),
    path('wallet/', include("wallet.urls")),
    path('', include("food.urls")),
    path('', include("order.urls")),
    path('', include("review.urls")),
    
]

food/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart

urlpatterns = [
    path('add-to-cart/<int:pk>/',  add_to_cart, name="add_to_cart"),
    path('remote-from-cart/<int:pk>/',  remove_from_cart, name="remove_from_cart")
]

review/urls.py
from django.urls import path
from .views import AddReviewView, ReviewListView

urlpatterns = [
    path('review/<int:pk>/', AddReviewView.as_view(), name="review"),
    path('reviews/', ReviewListView.as_view(), name="reviews")
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from food.models import Food

# Create your models here.
class ReviewModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    heading = models.CharField(max_length=100, verbose_name="Title")
    review = models.TextField()
    date = models.DateField(auto_now_add=True)
    item = models.ForeignKey(Food, on_delete=models.CASCADE, related_name="review")

    def __str__(self):
        return self.user.username

review/forms.py
from django import forms
from .models import ReviewModel


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewModel
        fields = ['heading', 'review', 'rating']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.food = kwargs.pop('food')
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                
                'class' : (
                    'appearance-none block w-full '
                    'text-gray-700 border border-red-700 bg-zinc-50 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-zinc-50 shadow-none'
                ) 
            })
        
        self.fields['review'].widget.attrs.update({
            'class': (
                'appearance-none block w-full '
                'text-gray-700 border border-red-700 bg-zinc-50 rounded '
                'py-3 px-4 leading-tight focus:outline-none '
                'focus:bg-zinc-50 shadow-none'
                ' h-40'
            )
        })

    def save(self, commit=True):
        review = super().save(commit=False)

        if commit is True:
            review.user = self.user
            review.item = self.food
        
            review.save()

        return review

review/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView
from .models import ReviewModel
from .forms import ReviewForm
from django.urls import reverse_lazy
from food.models import Food
from django.contrib.auth.mixins import LoginRequiredMixin


class AddReviewView(CreateView, LoginRequiredMixin):
    model = ReviewModel
    form_class = ReviewForm
    template_name = 'add_review.html'
    success_url = reverse_lazy('reviews')
    pk_url_kwarg = 'pk'

    def get_form_kwargs(self):
        food_pk = self.kwargs.get(self.pk_url_kwarg)
        food = get_object_or_404(Food, pk=food_pk)
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user,
            'food': food,
        })

        return kwargs
    
    def get_context_data(self, **kwargs: Any):
        food_pk = self.kwargs.get(self.pk_url_kwarg)
        food = get_object_or_404(Food, pk=food_pk)
        context = super().get_context_data(**kwargs)
        context.update({
            'food': food,
        })
        return context
    

class ReviewListView(ListView, LoginRequiredMixin):
    template_name = 'reviews.html'
    model = ReviewModel
    
    def get_queryset(self):
        queryset = super().get_queryset().filter(
            user=self.request.user
        )
       
        return queryset

review/templates/add_review.html
{% extends 'base.html' %}

{% block main %}

{% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div id="toast-danger" class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
        </svg>
        <span class="sr-only">Error icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{error}}</div>
</div>
{% endfor %} {% endif %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div id="toast-danger" class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
        </svg>
        <span class="sr-only">Error icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{error}}</div>
</div>
{% endfor %} {% endif %}

<section class="mb-20">
    <h1 class="text-5xl font-bold text-red-950 text-center mb-10 mt-5 shadow-none">Review {{food.name}}</h1>
    <div class="flex justify-center">
        <form method="post" class="bg-zinc-50 w-[35%] rounded p-10">
            {% csrf_token %}
            <div class="flex justify-center">
                <div class="w-full">
                    <div>
                        <div class="flex text-2xl gap-2 justify-center my-5">
                            <i class="fa-solid fa-star cursor-pointer text-gray-500" id="1" onclick=handleClick(event)></i>
                            <i class="fa-solid fa-star cursor-pointer text-gray-500" id="2" onclick=handleClick(event)></i>
                            <i class="fa-solid fa-star cursor-pointer text-gray-500" id="3" onclick=handleClick(event)></i>
                            <i class="fa-solid fa-star cursor-pointer text-gray-500" id="4" onclick=handleClick(event)></i>
                            <i class="fa-solid fa-star cursor-pointer text-gray-500" id="5" onclick=handleClick(event)></i>
                        </div>
                    </div>
                    <div class="py-5">
                        <label for="{{form.heading.id_for_label}}">{{form.heading.label}}</label>
                        {{form.heading}}
                    </div>
                    <div class="py-5">
                        <label for="{{form.review.id_for_label}}">{{form.review.label}}</label>
                        {{form.review}}
                    </div>
                    <input type="number" name="rating" value="0" class="hidden appearance-none w-full text-gray-700 border border-red-700 bg-zinc-50 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-zinc-50 focus:border-red-700" required="" id="id_rating" autocomplete="off">
                    <button type="submit" class="w-full bg-red-700 text-white h-[50px] rounded-lg my-8">Post</button>
    
                </div>
            </div>
        </form>
    </div>
</section>

<script>
    const handleClick = (e) => {
        
        for(let i = 1; i <= 5; i++)
        {
            const star = document.getElementById(String(i))
            star.classList.remove("text-amber-400")
            star.classList.add("text-gray-500")
            
        }

        for(let i = 1; i <= e.target.id; i++)
        {
            const star = document.getElementById(String(i))
            star.classList.remove("text-gray-500")
            star.classList.add("text-amber-400")
        }

        rating = document.getElementById("id_rating")
        rating.value = e.target.id
    }
</script>

{% endblock main %}

review/templates/reviews.html
{% extends 'base.html' %}

{% block main %}

<section class="mb-20">
    <div class="flex flex-col items-center">
        <div class="w-11/12">
            <div class="flex justify-center">
                <div>
                    <h1 class="text-5xl text-red-950 font-bold mt-20 mb-10">Reviews</h1>
            <div>
                {% if object_list %}
                <div class="grid gap-3 grid-cols-3">
                    {% for review in object_list %}
                        <div class="w-[392px] min-h-[296px] bg-rose-50 p-6 rounded">
                            <div>
                                <div class="flex gap-1  my-5 rating" id="{{review.rating}} {{review.pk}} rating">
                                    <i class="fa-solid fa-star cursor-pointer text-gray-500" id="1 {{review.pk}}"></i>
                                    <i class="fa-solid fa-star cursor-pointer text-gray-500" id="2 {{review.pk}}"></i>
                                    <i class="fa-solid fa-star cursor-pointer text-gray-500" id="3 {{review.pk}}"></i>
                                    <i class="fa-solid fa-star cursor-pointer text-gray-500" id="4 {{review.pk}}"></i>
                                    <i class="fa-solid fa-star cursor-pointer text-gray-500" id="5 {{review.pk}}"></i>
                                </div>
                                <div style="display: grid;
                                grid-template-rows: auto 1fr auto;
                                min-height: 200px;">
                                    <div style="display: flex;
                                    align-items: center;">
                                        <div>
                                            <h3 class="font-semibold">{{review.heading}}</h3>
                                            <p>
                                                {{review.review}}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="mt-auto mb-auto" style="margin-top: auto; margin-bottom: auto;">
                                        <p><span class="font-medium">{{review.item.name}}</span>, <span class="font-light">{{review.date}}</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% else %}
                <div>
                    <h3 class="font-xl font-semibold">No item has been reviewed.</h3>
                </div>
                {% endif %}
            </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    const handleRating = () => {
        let elements = document.getElementsByClassName("rating")
        Array.from(elements).forEach((element) => {
            let rating = element.id
            rating_arr = rating.split(" ")
            rating = rating_arr[0]
            id = rating_arr[1]
            for(let i = 1; i <= rating; i++)
            {   
                elem_id = String(i) + " " + String(id)
                console.log(elem_id)
                const star = document.getElementById(elem_id)
                star.classList.remove("text-gray-500")
                star.classList.add("text-yellow-300")
            }  
        })
    }
    handleRating()
</script>

{% endblock %}